defaults:
- preprocess: default
- dataset: default
- model: vqw2v_enc_tricodec
- train: default
log_dir: pl_log
debug: false
ckpt: null
id: null
input_dir: null
output_dir: null
hydra:
  output_subdir: hydra
  job:
    chdir: true
cache_dir: null
voice_conversion: vc
